//! # Unified Vector-Graph Fusion Engine (In-Memory GraphRAG)
//!
//! Provides zero-network, single-pass unified execution between HNSW high-dimensional
//! vector embeddings and property knowledge graphs. Eliminates the "GraphRAG synchronization gap"
//! by executing vector-guided graph traversal and graph-constrained vector search within
//! the exact same in-process memory space.

use crate::graph::{Edge, GraphStore, Vertex};
use faizdb_vector::hnsw::{HnswConfig, HnswIndex, VectorSearchResult};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

/// A node within a fused Vector-Graph RAG retrieval result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FusedRagNode {
    /// The graph vertex
    pub vertex: Vertex,
    /// Distance/similarity from the original query embedding (if directly seeded or nearest seed)
    pub seed_similarity: f32,
    /// Topological hop distance from the nearest seed node
    pub hop_distance: usize,
    /// Combined hybrid relevance score: alpha * similarity + (1 - alpha) * topology
    pub hybrid_score: f32,
}

/// Complete structured context generated by the fused VectorGraph engine for LLM prompt injection
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FusedRagContext {
    /// Seed matches identified via ANN vector search
    pub seed_matches: Vec<VectorSearchResult>,
    /// Entities retrieved with hybrid ranking scores
    pub nodes: Vec<FusedRagNode>,
    /// Relationships connecting the retrieved entities
    pub edges: Vec<Edge>,
    /// Clean formatted Markdown ready for LLM prompt injection
    pub formatted_markdown: String,
}

/// Unified VectorGraph combining HNSW similarity search with property graph traversals
pub struct VectorGraph {
    /// In-memory graph store holding vertices, edges, and adjacency lists
    pub graph: GraphStore,
    /// HNSW vector index mapping vertex IDs to high-dimensional embeddings
    pub vector_index: HnswIndex,
}

impl VectorGraph {
    /// Initialize a new VectorGraph with the given HNSW configuration
    pub fn new(vector_config: HnswConfig) -> Self {
        Self {
            graph: GraphStore::new(),
            vector_index: HnswIndex::new(vector_config),
        }
    }

    /// Insert a graph vertex along with its high-dimensional vector embedding in a single atomic call
    pub fn insert_node_with_vector(
        &mut self,
        vertex: Vertex,
        embedding: Vec<f32>,
    ) -> Result<(), String> {
        let id = vertex.id.clone();
        self.graph.add_vertex(vertex);
        self.vector_index.insert(&id, embedding)
    }

    /// Insert an edge connecting two vertices
    pub fn add_edge(&mut self, edge: Edge) {
        self.graph.add_edge(edge);
    }

    /// Delete a node: cleans up graph vertices, incident edges, and tombstones the vector embedding
    pub fn delete_node(&mut self, vertex_id: &str) -> bool {
        let graph_deleted = self.graph.remove_vertex(vertex_id);
        let vector_deleted = self.vector_index.delete(vertex_id);
        graph_deleted || vector_deleted
    }

    /// Vector-Guided GraphRAG Traversal (Single-Pass):
    /// 1. Finds the top-k nearest semantic seed nodes using HNSW ANN search.
    /// 2. Expands the local relationship neighborhood (BFS up to `max_depth`) from those seeds.
    /// 3. Computes a hybrid relevance score:
    ///    `Score(v) = alpha * seed_sim + (1 - alpha) * (1 / (1 + hop_distance))`
    /// 4. Emits a clean structured Markdown context for LLM prompt injection.
    pub fn vector_guided_rag(
        &self,
        query_vector: &[f32],
        top_k_seeds: usize,
        max_depth: usize,
        relation_filter: Option<&str>,
        alpha: f32,
    ) -> Result<FusedRagContext, String> {
        if top_k_seeds == 0 {
            return Err("top_k_seeds must be greater than 0".to_string());
        }

        // Step 1: ANN search for semantic entry vertices
        let seeds = self.vector_index.search(query_vector, top_k_seeds);
        if seeds.is_empty() {
            return Ok(FusedRagContext {
                seed_matches: Vec::new(),
                nodes: Vec::new(),
                edges: Vec::new(),
                formatted_markdown: "# GraphRAG Context\n\nNo semantic seed nodes found.\n".into(),
            });
        }

        let mut node_scores: HashMap<String, (f32, usize, f32)> = HashMap::new();
        let alpha = alpha.clamp(0.0, 1.0);

        // Step 2: For each seed, explore local topological neighborhood in-memory
        for seed in &seeds {
            let seed_sim = seed.similarity;
            let steps = self
                .graph
                .traverse_bfs(&seed.id, max_depth, relation_filter);

            for step in steps {
                let hop = step.depth;
                let hop_factor = 1.0 / (1.0 + hop as f32);
                let hybrid_score = (alpha * seed_sim) + ((1.0 - alpha) * hop_factor);

                node_scores
                    .entry(step.vertex_id.clone())
                    .and_modify(|(best_sim, best_hop, best_score)| {
                        if hybrid_score > *best_score {
                            *best_sim = seed_sim;
                            *best_hop = hop;
                            *best_score = hybrid_score;
                        }
                    })
                    .or_insert((seed_sim, hop, hybrid_score));
            }
        }

        // Materialize ranked nodes
        let mut ranked_nodes: Vec<FusedRagNode> = Vec::with_capacity(node_scores.len());
        for (v_id, (sim, hop, score)) in node_scores {
            if let Some(v) = self.graph.get_vertex(&v_id) {
                ranked_nodes.push(FusedRagNode {
                    vertex: v.clone(),
                    seed_similarity: sim,
                    hop_distance: hop,
                    hybrid_score: score,
                });
            }
        }

        // Sort descending by hybrid score
        ranked_nodes.sort_by(|a, b| {
            b.hybrid_score
                .partial_cmp(&a.hybrid_score)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        // Collect all edges linking the retrieved nodes
        let retrieved_id_set: HashSet<String> =
            ranked_nodes.iter().map(|n| n.vertex.id.clone()).collect();

        let mut collected_edges = Vec::new();
        for node in &ranked_nodes {
            for edge in self.graph.edges(&node.vertex.id, crate::graph::Direction::Outgoing, relation_filter) {
                if retrieved_id_set.contains(&edge.to) {
                    collected_edges.push((*edge).clone());
                }
            }
        }

        // Format Markdown context for prompt injection
        let mut md = String::new();
        md.push_str("# 🧠 FaizDB Fused GraphRAG Context\n\n");

        md.push_str("## 🎯 Semantic Seed Vertices\n");
        for seed in &seeds {
            md.push_str(&format!(
                "- Seed Node `{}` (Cosine Similarity: `{:.4}`)\n",
                seed.id, seed.similarity
            ));
        }

        md.push_str("\n## 🌐 Retrieved Entities (Ranked by Hybrid Relevance)\n");
        for n in &ranked_nodes {
            md.push_str(&format!(
                "- **{}** (`{}`) [Score: `{:.3}`, Hops: `{}`]\n",
                n.vertex.label, n.vertex.id, n.hybrid_score, n.hop_distance
            ));
            if !n.vertex.properties.fields.is_empty() {
                if let Ok(p_str) = serde_json::to_string(&n.vertex.properties) {
                    md.push_str(&format!("  - Attributes: `{p_str}`\n"));
                }
            }
        }

        md.push_str("\n## 🔗 Topological Relationships\n");
        if collected_edges.is_empty() {
            md.push_str("- No explicit interconnecting edges in subgraph.\n");
        } else {
            for e in &collected_edges {
                md.push_str(&format!(
                    "- (`{}`) -[:{}]-> (`{}`) [weight: {}]\n",
                    e.from, e.relation, e.to, e.weight
                ));
            }
        }

        Ok(FusedRagContext {
            seed_matches: seeds,
            nodes: ranked_nodes,
            edges: collected_edges,
            formatted_markdown: md,
        })
    }

    /// Graph-Constrained Vector Search:
    /// Executes high-dimensional vector search restricted strictly to vertices reachable
    /// within a subgraph starting from `subgraph_root` up to `max_depth`.
    /// Solves the multi-tenant / department boundary problem in enterprise RAG without post-filtering.
    pub fn graph_constrained_vector_search(
        &self,
        query_vector: &[f32],
        top_k: usize,
        subgraph_root: &str,
        max_depth: usize,
        relation_filter: Option<&str>,
    ) -> Vec<VectorSearchResult> {
        // Collect allowable vertex IDs via BFS traversal
        let steps = self
            .graph
            .traverse_bfs(subgraph_root, max_depth, relation_filter);

        let allowed_ids: HashSet<String> = steps.into_iter().map(|s| s.vertex_id).collect();

        if allowed_ids.is_empty() {
            return Vec::new();
        }

        // Single-pass filtered vector search
        self.vector_index
            .search_with_filter(query_vector, top_k, |id| allowed_ids.contains(id))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::Vertex;
    use faizdb_core::document::model::Document;
    use faizdb_vector::distance::DistanceMetric;

    #[test]
    fn test_fused_vector_graph_rag_lifecycle() {
        let dim = 3;
        let config = HnswConfig::new(dim, DistanceMetric::Cosine);
        let mut vg = VectorGraph::new(config);

        // 1. Insert vertices with semantic embeddings
        let mut v1 = Vertex::new("incident_404", "Incident");
        let mut p1 = Document::new();
        p1.set("severity", "critical");
        v1.properties = p1;
        vg.insert_node_with_vector(v1, vec![1.0, 0.0, 0.0]).unwrap();

        let mut v2 = Vertex::new("db_cluster_alpha", "Infrastructure");
        let mut p2 = Document::new();
        p2.set("region", "ap-southeast-1");
        v2.properties = p2;
        vg.insert_node_with_vector(v2, vec![0.9, 0.1, 0.0]).unwrap();

        let mut v3 = Vertex::new("user_lead_engineer", "Engineer");
        let mut p3 = Document::new();
        p3.set("name", "Faiz");
        v3.properties = p3;
        vg.insert_node_with_vector(v3, vec![0.0, 1.0, 0.0]).unwrap();

        let v4 = Vertex::new("unrelated_marketing", "Document");
        vg.insert_node_with_vector(v4, vec![0.0, 0.0, 1.0]).unwrap();

        // 2. Connect topology via edges
        vg.add_edge(Edge::new(
            "incident_404",
            "db_cluster_alpha",
            "AFFECTS",
        ));
        vg.add_edge(Edge::new(
            "user_lead_engineer",
            "db_cluster_alpha",
            "MAINTAINS",
        ));

        // 3. Vector-Guided GraphRAG Query: query vector close to incident_404 [1.0, 0.05, 0.0]
        let query = vec![1.0, 0.05, 0.0];
        let rag_context = vg
            .vector_guided_rag(&query, 1, 2, None, 0.7)
            .expect("RAG traversal must succeed");

        assert_eq!(rag_context.seed_matches.len(), 1);
        assert_eq!(rag_context.seed_matches[0].id, "incident_404");

        // The traversal from incident_404 should reach db_cluster_alpha
        let node_ids: Vec<String> = rag_context
            .nodes
            .iter()
            .map(|n| n.vertex.id.clone())
            .collect();
        assert!(node_ids.contains(&"incident_404".to_string()));
        assert!(node_ids.contains(&"db_cluster_alpha".to_string()));

        // Unrelated marketing should NOT be included
        assert!(!node_ids.contains(&"unrelated_marketing".to_string()));

        // Edge between incident_404 and db_cluster_alpha must be captured
        assert_eq!(rag_context.edges.len(), 1);
        assert_eq!(rag_context.edges[0].relation, "AFFECTS");

        // Verify Markdown is generated cleanly
        assert!(rag_context.formatted_markdown.contains("# 🧠 FaizDB Fused GraphRAG Context"));
        assert!(rag_context.formatted_markdown.contains("Incident"));

        // 4. Graph-Constrained Vector Search
        // Query for [0.8, 0.2, 0.0] restricted to the subgraph rooted at incident_404
        let constrained = vg.graph_constrained_vector_search(&query, 5, "incident_404", 2, None);

        // Constrained should only find incident_404 and db_cluster_alpha, not unrelated_marketing
        assert_eq!(constrained.len(), 2);
        let found_ids: Vec<String> = constrained.into_iter().map(|r| r.id).collect();
        assert!(found_ids.contains(&"incident_404".to_string()));
        assert!(found_ids.contains(&"db_cluster_alpha".to_string()));
        assert!(!found_ids.contains(&"unrelated_marketing".to_string()));

        // 5. Test Node Deletion Consistency
        assert!(vg.delete_node("incident_404"));
        assert_eq!(vg.graph.vertex_count(), 3);
        assert!(!vg.vector_index.contains_id("incident_404"));
    }
}
